
export const FUN_COLORS = [
    '#FF5733', // Vibrant Orange
    '#24D14C', // Bright Green
    '#FF33A1', // Hot Pink
    '#00CCDD', // Bright Teal
    '#FF3333', // Fiery Red
    '#C433FF', // Vivid Violet
    '#FFB733', // Bright Gold
    '#33A1FF', // Vivid Cerulean
    '#FF66CC', // Playful Magenta
    '#41A36F', // **Sea Green** 
];

export const LOGO = process.env.PUBLIC_URL + '/data/JOAKS_BGLESS.png';
export const HOME_LOGO = process.env.PUBLIC_URL + '/data/JOAKS.png';

export const LOADING_GIF = process.env.PUBLIC_URL + '/data/JOAKS.GIF';

export const AVATAR_LIST = [
    {
        name: 'pear',
        happy: process.env.PUBLIC_URL + '/data/avatars/pear/IMG_2602.PNG',
        neutral: process.env.PUBLIC_URL + '/data/avatars/pear/IMG_2601.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/pear/IMG_2600.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/pear/IMG_2599.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/pear/IMG_2597.PNG',
        sad_phrase: `A-pear-antly I'm bad at this`,
        happy_phrase: 'Pear-fect!',
    },
    {
        name: 'gummy-bear',
        neutral: process.env.PUBLIC_URL + '/data/avatars/gummy-bear/IMG_2621.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/gummy-bear/IMG_2620.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/gummy-bear/IMG_2625.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/gummy-bear/IMG_2619.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/gummy-bear/IMG_2617.PNG',
        sad_phrase: 'Well this is a sticky situation.',
        happy_phrase: 'For the cinna-win!',
    },
    {
        name: 'pea',
        neutral: process.env.PUBLIC_URL + '/data/avatars/pea/IMG_2636.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/pea/IMG_2639.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/pea/IMG_2637.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/pea/IMG_2640.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/pea/IMG_2638.PNG',
        sad_phrase: 'Stop peas.',
        happy_phrase: 'Peas out!',
    },
    {
        name: 'ghosty',
        neutral: process.env.PUBLIC_URL + '/data/avatars/ghosty/IMG_2610.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/ghosty/IMG_2606.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/ghosty/IMG_2608.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/ghosty/IMG_2612.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/ghosty/IMG_2603.PNG',
        sad_phrase: 'Crushed my spirit.',
        happy_phrase: 'Boo yah!',
    },
    {
        name: 'bell-pepper',
        neutral: process.env.PUBLIC_URL + '/data/avatars/bell-pepper/IMG_2371.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/bell-pepper/IMG_2375.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/bell-pepper/IMG_2376.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/bell-pepper/IMG_2373.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/bell-pepper/IMG_2374.PNG',
        sad_phrase: 'I got my bell rung.',
        happy_phrase: 'Ding ding! Ring the bell.',
    },
    {
        name: 'panda',
        neutral: process.env.PUBLIC_URL + '/data/avatars/panda/57bb9204-6ad0-4e71-bb57-597ddee9608d.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/panda/357d83cb-01f8-4792-b91b-184b72b7f147.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/panda/d1dde474-2ff6-4272-af16-56ed1eb6dd37.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/panda/f481cae1-c6ce-4578-8d74-84cf79c7357a.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/panda/79684e4a-d9b0-4533-b5c8-4d556f44ccac.png.PNG',
        sad_phrase: 'This is panda-monium.',
        happy_phrase: 'That really panda-out.',
    },
    {
        name: 'giraffe',
        neutral: process.env.PUBLIC_URL + '/data/avatars/giraffe/IMG_2296.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/giraffe/IMG_2295.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/giraffe/IMG_2292.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/giraffe/IMG_2294.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/giraffe/IMG_2293.PNG',
        sad_phrase: 'This is what happens when I stick my neck out.',
        happy_phrase: 'You bet giraffe I won!',
    },
    {
        name: 'bear',
        neutral: process.env.PUBLIC_URL + '/data/avatars/bear/IMG_2216.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/bear/IMG_2214.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/bear/dae8ff2c-c9a4-4b9d-980b-4cc8ba8e71f3.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/bear/579ae019-4343-4d39-b5ee-583f127f2d6d.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/bear/c870bd2f-902f-4f47-973a-4cdd62acbfb4.png.PNG',
        sad_phrase: 'Unbearable.',
        happy_phrase: 'Bearly made it.',
    },
    {
        name: 'goldfish',
        neutral: process.env.PUBLIC_URL + '/data/avatars/goldfish/8d598a94-f594-4d2b-8184-32b1ccd052d4.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/goldfish/ed5d6dba-3455-4455-b74b-518623ad185a.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/goldfish/136ec484-040d-41bc-96a9-469d8787bb3a.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/goldfish/32a003a6-ae77-4eb3-9adf-2b58454ecda5.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/goldfish/41ff5134-3321-4193-8889-1070a1e5dab8.png.PNG',
        sad_phrase: 'All that glitters...',
        happy_phrase: 'I feel so bubbly!',
    },
    {
        name: 'puppy',
        neutral: process.env.PUBLIC_URL + '/data/avatars/puppy/f35e0167-14c0-46d4-948a-7f2ca3dbca35.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/puppy/bd05d920-0639-46e3-8b3f-1d33f44b8c15.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/puppy/44438836-2e80-4186-b632-cfc8c318122c.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/puppy/2a9acbf6-0995-4365-a105-0d5b60c36d8e.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/puppy/98eda01e-f9da-460e-90b8-fcd9f4741464.png.png',
        sad_phrase: 'That was ruff.',
        happy_phrase: 'Woof!',
    },
    {
        name: 'tooth',
        neutral: process.env.PUBLIC_URL + '/data/avatars/tooth/0f34dd5e-27e7-4135-bb49-9002865035fe.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/tooth/8b65a908-6f0f-4bb4-a5f6-750cf8f4d73a.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/tooth/9ed875e5-4115-4ab8-b6ca-a2752abfe398.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/tooth/2b9261fc-daeb-4a06-a198-2a6895294fe9.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/tooth/a32f7938-00bd-4009-b998-3b61477e4628.png.PNG',
        sad_phrase: 'I ache...',
        happy_phrase: 'Sweet!',
    },
    {
        name: 'unicorn',
        neutral: process.env.PUBLIC_URL + '/data/avatars/unicorns/d70ecc72-bf43-4e2f-acc7-cbcae06adaa2.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/unicorns/2302bf13-9a2e-41e0-b8d3-c863b9a5ce1b.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/unicorns/c648445b-5e74-4e91-83af-9c727ea5c0c7.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/unicorns/3b50e3c8-4b5c-4180-957f-b4eaf46bcc4d.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/unicorns/f336d1a7-5135-4b42-b046-1fb66474b492.png.PNG',
        sad_phrase: 'Unbelievable.',
        happy_phrase: 'Magical!',
    },
    {
        name: 'goose',
        neutral: process.env.PUBLIC_URL + '/data/avatars/goose/c835fd16-77eb-4513-af6f-a9e3ee0443f3.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/goose/e5dc8eb2-3635-4077-83ed-00957c4e028e.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/goose/ddc540ad-27d0-4c45-b765-87f134d6e8a1.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/goose/f484dd00-95a8-4f70-ab4c-1f052bd8d895.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/goose/IMG_2390.PNG',
        sad_phrase: 'That was silly.',
        happy_phrase: 'Take a gander at this action!',
    },
    {
        name: 'alien',
        neutral: process.env.PUBLIC_URL + '/data//avatars/alien/IMG_2107.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2159.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2108.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2109.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2158.PNG',
        sad_phrase: 'I spaced out...',
        happy_phrase: 'Outta this world!',
    },
    {
        name: 't-rex',
        neutral: process.env.PUBLIC_URL + '/data/avatars/t-rex/02a2b07f-a4f5-417f-ba35-d8864440c689.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/t-rex/fa90abe7-5a58-4361-afe0-26d5da673579.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/t-rex/6d65d4a0-934c-4fc4-8d75-cf2c270f6a0c.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/t-rex/fa90abe7-5a58-4361-afe0-26d5da673579.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/t-rex/fabc5070-9645-4a61-8ae4-e182d8b65a72.png.PNG',
        sad_phrase: 'Hard to swallow.',
        happy_phrase: 'Get T Wrecked',
    },
    {
        name: 'robot',
        neutral: process.env.PUBLIC_URL + '/data/avatars/robot/c45f1039-34e9-411a-8c47-d07e3c29ec03.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/robot/Untitled design 3.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/robot/Untitled design 4.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/robot/c45f1039-34e9-411a-8c47-d07e3c29ec03.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/robot/Untitled design 5.PNG',
        sad_phrase: 'Does not compute...',
        happy_phrase: 'My logic is undeniable.',
    },
    {
        name: 'marshmallow',
        neutral: process.env.PUBLIC_URL + '/data/avatars/marshmallow/IMG_2234.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/marshmallow/fa04d0d8-0d50-4fa8-9c1f-6d905e055594.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/marshmallow/IMG_2244.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/marshmallow/IMG_2242.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/marshmallow/IMG_2240.PNG',
        sad_phrase: 'I got burnt...',
        happy_phrase: 'Stay mallow!',
    },
    {
        name: 'pepper',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/pepper/IMG_2358.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/pepper/IMG_2357.PNG',
        neutral: process.env.PUBLIC_URL + '/data/avatars/pepper/IMG_2361.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/pepper/IMG_2359.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/pepper/IMG_2360.PNG',
        sad_phrase: 'That stings.',
        happy_phrase: 'I am hot hot hot!',
    },
    {
        name: 'potato',
        neutral: process.env.PUBLIC_URL + '/data/avatars/potato/IMG_2303.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/potato/IMG_2304.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/potato/IMG_2307.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/potato/IMG_2308.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/potato/IMG_2306.PNG',
        sad_phrase: 'I was no mash for you.',
        happy_phrase: 'Nice fry!',
    },
    {
        name: 'ninja',
        neutral: process.env.PUBLIC_URL + '/data/avatars/ninja/IMG_2280.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/ninja/IMG_2283.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/ninja/IMG_2281.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/ninja/IMG_2284.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/ninja/IMG_2282.PNG',
        sad_phrase: 'Dishonor.',
        happy_phrase: `Bet ya didn't see that coming!`,
    },
    {
        name: 'star',
        neutral: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1851.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1855.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1854.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1853.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1852.PNG',
        sad_phrase: 'Sirius-ly?',
        happy_phrase: 'Twinkle twinkle big star.',
    },
    {
        name: 'gator',
        neutral: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1954.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1957.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1955.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1958.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1956.PNG',
        sad_phrase: 'What a croc!',
        happy_phrase: 'See ya later!',
    },
    {
        name: 'duck',
        neutral: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2050.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2054.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2051.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2049.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/duck/3b87e055-22e5-44e3-8867-7140bee593b3.png.PNG',
        sad_phrase: 'Quack.',
        happy_phrase: 'Quack!',
    },
    {
        name: 'lion',
        neutral: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2067.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2072.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2069.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2068.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2070.PNG',
        sad_phrase: `I'm not gonna sleep tonight.`,
        happy_phrase: 'Feels good to be king.',
    },
    {
        name: 'bacon',
        neutral: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1997.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1994.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1996.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1998.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1995.PNG',
        sad_phrase: 'I miss being a pig...',
        happy_phrase: 'Add a little sizzle to that burn.',
    },
    {
        name: 'banana',
        neutral: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1925.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1927.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1926.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1923.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1924.PNG',
        sad_phrase: 'Sadnana',
        happy_phrase: 'Gladnana',
    },
    {
        name: 'bread',
        neutral: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2042.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_1911.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2044.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2043.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2041.PNG',
        sad_phrase: 'At yeast I tried.',
        happy_phrase: 'I kneaded that.',
    },
    {
        name: 'egg',
        neutral: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2119.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2118.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2122.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2121.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2120.PNG',
        sad_phrase: 'Looking for the sunny side...',
        happy_phrase: 'Yokes on you!',
    },
    {
        name: 'shark',
        neutral: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2103.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2101.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2105.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2104.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2102.PNG',
        sad_phrase: `I'm such a hammerhead.`,
        happy_phrase: 'Take a bite out of the competition.',
    },
    {
        name: 'cactus',
        neutral: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1988.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1990.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1991.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1992.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1989.PNG',
        sad_phrase: 'I could use a hug...',
        happy_phrase: 'Now for some desert',
    },
    {
        name: 'bull',
        neutral: process.env.PUBLIC_URL + '/data/avatars/bull/IMG_2198.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/bull/IMG_2196.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/bull/IMG_2197.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/bull/IMG_2199.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/bull/IMG_2195.PNG',
        sad_phrase: `What a load of bull`,
        happy_phrase: 'Bull-eive it',
    },
    {
        name: 'apple',
        neutral: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1916.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1913.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1914.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1915.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1917.PNG',
        sad_phrase: 'I seed what you did there.',
        happy_phrase: 'Easy as pie!',
    },
    {
        name: 'cloud',
        neutral: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2014.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2012.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2013.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2011.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2015.PNG',
        sad_phrase: 'Looking for a silver lining.',
        happy_phrase: 'Sorry to rain on your parade.',
    },
    {
        name: 'moose',
        neutral: process.env.PUBLIC_URL + '/data/avatars/moose/IMG_2314.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/moose/IMG_2311.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/moose/IMG_2313.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/moose/IMG_2312.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/moose/IMG_2310.PNG',
        sad_phrase: `Just trying to make the moose of this.`,
        happy_phrase: 'Antler-ned your lesson yet?',
    },
    {
        name: 'diamond',
        neutral: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2123.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2124.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2126.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2125.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2128.PNG',
        sad_phrase: 'I was under pressure.',
        happy_phrase: 'Solid',
    },
    {
        name: 'donut',
        neutral: process.env.PUBLIC_URL + '/data/avatars/donut/IMG_1785.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/donut/055aa2ae-8774-4130-8171-8a467c2a06f9.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/donut/27429fc7-533d-4a11-81d4-1c402bed8bb3.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/donut/27429fc7-533d-4a11-81d4-1c402bed8bb3.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/donut/4f93c576-adee-47d0-80ce-ba9b28267f7c.png.PNG',
        sad_phrase: 'I just donut understand.',
        happy_phrase: 'You made my hole day.',
    },
    {
        name: 'sun',
        neutral: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2016.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2017.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2016.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2018.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2021.PNG',
        sad_phrase: 'That lacked some flare.',
        happy_phrase: 'It was a stroke of genius!',
    },
    {
        name: 'Whale',
        neutral: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_2565.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/whale/971129d8-db38-49ae-9af5-3c9d74421751.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_2574.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_2572.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_2566.PNG',
        sad_phrase: 'Oh whale.',
        happy_phrase: 'Krilling it',
    },
    {
        name: 'pineapple',
        neutral: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1907.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1906.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1908.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1908.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1909.PNG',
        sad_phrase: 'Now I feel like a whine-apple.',
        happy_phrase: 'They call me the fine-apple.',
    },
    {
        name: 'flame',
        neutral: process.env.PUBLIC_URL + '/data/avatars/flame/5c53edc8-7868-4307-8885-ebd57801375f.png.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/flame/98c709e3-efaa-46f8-879e-39cbef65c4a1.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/flame/5c7233a2-7094-4c44-8e31-ee9be819418b.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/flame/e8bd69f6-abeb-4f6a-9e0b-b5fe89011f85.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/flame/aec1d0f1-aa02-4949-940b-0a82b428f896.png.PNG',
        sad_phrase: 'I feel so put out by this.',
        happy_phrase: `I'm on fire!`,
    },
    {
        name: 'lightbulb',
        neutral: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2036.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2032.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2033.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2035.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2034.PNG',
        sad_phrase: `I'm feeling burned out.`,
        happy_phrase: 'That was lit.',
    },
    {
        name: 'ghost',
        neutral: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2139.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2141.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2139.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2161.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2160.PNG',
        sad_phrase: `I'm gonna leave you on read.`,
        happy_phrase: `I'm so happy I could die!`,
    },
    {
        name: 'snowman',
        neutral: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2087.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2084.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2090.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2089.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2088.PNG',
        sad_phrase: 'Is it getting hot in here?',
        happy_phrase: 'Stay frosty!',
    },
    {
        name: 'watermelon',
        neutral: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2001.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2004.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2005.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2003.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2002.PNG',
        sad_phrase: 'Water you looking at?',
        happy_phrase: 'One in a melon!',
    },
    {
        name: 'heart',
        neutral: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2061.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2058.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2060.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2059.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2062.PNG',
        sad_phrase: 'That broke me.',
        happy_phrase: 'Follow me next time.',
    },
    {
        name: 'rock',
        neutral: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1985.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1984.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1980.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1981.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1982.PNG',
        sad_phrase: 'First paper, now this.',
        happy_phrase: 'Rock beats you too!',
    },
    {
        name: 'pirate',
        neutral: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2091.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2092.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2091.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2093.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2095.PNG',
        sad_phrase: 'You kicked my booty.',
        happy_phrase: 'Yo ho!',
    },
    {
        name: 'horse',
        neutral: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1952.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1950.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1951.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1949.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1946.PNG',
        sad_phrase: 'I was just horsing around.',
        happy_phrase: 'Why the long face?',
    },
    {
        name: 'icecream',
        neutral: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1896.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1898.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1897.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1895.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1893.PNG',
        sad_phrase: 'Now that was cold.',
        happy_phrase: 'Chill.',
    },
    {
        name: 'leaf',
        neutral: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1878.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1879.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1881.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1882.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1880.PNG',
        sad_phrase: 'You blew me away.',
        happy_phrase: 'Leaf it to me.',
    },
    {
        name: 'orange',
        neutral: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1918.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1920.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1919.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1921.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1922.PNG',
        sad_phrase: 'That was less than a-peeling.',
        happy_phrase: 'Orange you glad I came?',
    },
    {
        name: 'cat',
        neutral: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1929.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1930.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1928.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1928.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1928.PNG',
        sad_phrase: 'Feline that one...',
        happy_phrase: 'How do you like meow?',
    },
    {
        name: 'cupcake',
        neutral: process.env.PUBLIC_URL + '/data/avatars/cupcake/IMG_2364.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/cupcake/IMG_2363.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/cupcake/IMG_2369.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/cupcake/IMG_2368.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/cupcake/IMG_2366.PNG',
        sad_phrase: 'That was not sweet.',
        happy_phrase: 'Piece of cupcake!',
    },
    {
        name: 'poop',
        neutral: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1974.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1969.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1973.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1972.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1971.PNG',
        sad_phrase: 'Poop!',
        happy_phrase: 'I can do this crap all day!',
    },
    {
        name: 'astronaut',
        neutral: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2152.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2149.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2152.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2152.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2151.PNG',
        sad_phrase: 'Houston, we have a problem.',
        happy_phrase: 'One small point for me.',
    },
    {
        name: 'raccoon',
        neutral: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1941.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1940.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1939.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_2064.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1962.PNG',
        sad_phrase: 'This is garbage.',
        happy_phrase: 'I made out like a bandit.',
    },
    {
        name: 'rain',
        neutral: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2022.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2024.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2023.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2026.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2025.PNG',
        sad_phrase: 'Tut tut sounds like pain.',
        happy_phrase: 'Rain dropped the mic.',
    },
    {
        name: 'starfish',
        neutral: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2157.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2156.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2154.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2155.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2153.PNG',
        sad_phrase: 'Something smells star-fishy',
        happy_phrase: `I'll make you sea stars!`,
    },
]




// {
//     name: '',
//     neutral: process.env.PUBLIC_URL + '',
//     happy: process.env.PUBLIC_URL + '',
//     suspicious: process.env.PUBLIC_URL + '',
//     nervous: process.env.PUBLIC_URL + '',
//     sad: process.env.PUBLIC_URL + '',
//     sad_phrase: '',
//     happy_phrase: '',
// },