
export const FUN_COLORS = [
    '#FF5733', // Vibrant Orange
    '#33FF57', // Bright Green
    '#3357FF', // Bold Blue
    '#FF33A1', // Hot Pink
    '#33FFF5', // Aqua Blue
    '#FF8C33', // Warm Amber
    '#8C33FF', // Electric Purple
    '#FF3333'  // Fiery Red
  ];

export const AVATAR_LIST = [
    {
        name: 'star',
        neutral: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1851.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1855.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1854.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1853.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/star/IMG_1852.PNG',
        sad_phrase: 'Sirius-ly?',
        happy_phrase: 'Twinkle twinkle big star.',
    },
    {
        name: 'duck',
        neutral: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2050.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2054.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2051.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/duck/IMG_2049.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/duck/3b87e055-22e5-44e3-8867-7140bee593b3.png.PNG',
        sad_phrase: 'Quack.',
        happy_phrase: 'Quack!',
    },
    {
        name: 'lion',
        neutral: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2067.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2072.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2069.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2068.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/lion/IMG_2070.PNG',
        sad_phrase: `I'm not gonna sleep tonight.`,
        happy_phrase: 'Feels good to be king.',
    },
    {
        name: 'bacon',
        neutral: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1997.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1994.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1996.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1998.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/bacon/IMG_1995.PNG',
        sad_phrase: 'I miss being a pig...',
        happy_phrase: 'Add a little sizzle to that burn.',
    },
    {
        name: 'banana',
        neutral: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1925.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1927.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1926.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1923.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/banana/IMG_1924.PNG',
        sad_phrase: 'Sadnana',
        happy_phrase: 'Gladnana',
    },
    {
        name: 'bread',
        neutral: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2042.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_1911.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2044.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2043.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/bread/IMG_2041.PNG',
        sad_phrase: 'At yeast I tried.',
        happy_phrase: 'I kneaded that.',
    },
    {
        name: 'egg',
        neutral: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2119.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2118.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2122.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2121.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/egg/IMG_2120.PNG',
        sad_phrase: 'Looking for the sunny side...',
        happy_phrase: 'Yokes on you!',
    },
    {
        name: 'shark',
        neutral: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2103.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2101.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2105.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2104.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/shark/IMG_2102.PNG',
        sad_phrase: `I'm such a hammerhead.`,
        happy_phrase: 'Take a bite out of the competition.',
    },
    {
        name: 'cactus',
        neutral: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1988.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1990.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1991.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1992.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/cacti/IMG_1989.PNG',
        sad_phrase: 'I could use a hug...',
        happy_phrase: 'Now for some desert',
    },
    {
        name: 'apple',
        neutral: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1916.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1913.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1914.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1915.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/apple/IMG_1917.PNG',
        sad_phrase: 'I seed what you did there.',
        happy_phrase: 'Easy as pie!',
    },
    {
        name: 'cloud',
        neutral: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2014.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2012.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2013.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2011.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/cloud/IMG_2015.PNG',
        sad_phrase: 'Looking for a silver lining.',
        happy_phrase: 'Sorry to rain on your parade.',
    },
    {
        name: 'diamond',
        neutral: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2123.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2124.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2126.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2125.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/diamond/IMG_2128.PNG',
        sad_phrase: 'I was under pressure.',
        happy_phrase: 'Solid',
    },
    {
        name: 'donut',
        neutral: process.env.PUBLIC_URL + '/data/avatars/donut/IMG_1785.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/donut/055aa2ae-8774-4130-8171-8a467c2a06f9.png.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/donut/27429fc7-533d-4a11-81d4-1c402bed8bb3.png.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/donut/27429fc7-533d-4a11-81d4-1c402bed8bb3.png.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/donut/4f93c576-adee-47d0-80ce-ba9b28267f7c.png.PNG',
        sad_phrase: 'I just donut understand.',
        happy_phrase: 'You made my hole day.',
    },
    {
        name: 'gator',
        neutral: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1954.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1957.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1955.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1958.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/gator/IMG_1956.PNG',
        sad_phrase: 'What a croc!',
        happy_phrase: 'See ya later!',
    },
    {
        name: 'sun',
        neutral: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2016.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2017.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2016.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2018.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/sun/IMG_2021.PNG',
        sad_phrase: 'That lacked some flare.',
        happy_phrase: 'It was a stroke of genius!',
    },
    {
        name: 'lightbulb',
        neutral: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2036.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2032.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2033.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2035.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/lightbulb/IMG_2034.PNG',
        sad_phrase: `I'm feeling burned out.`,
        happy_phrase: 'That was lit.',
    },
    {
        name: 'ghost',
        neutral: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2139.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2141.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2139.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2161.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/ghost/IMG_2160.PNG',
        sad_phrase: `I'm gonna leave you on read.`,
        happy_phrase: `I'm so happy I could die!`,
    },
    {
        name: 'snowman',
        neutral: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2087.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2084.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2090.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2089.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/snowman/IMG_2088.PNG',
        sad_phrase: 'Is it getting hot in here?',
        happy_phrase: 'Stay frosty!',
    },
    {
        name: 'watermelon',
        neutral: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2001.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2004.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2005.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2003.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/watermelon/IMG_2002.PNG',
        sad_phrase: 'Water you looking at?',
        happy_phrase: 'One in a melon!',
    },
    {
        name: 'heart',
        neutral: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2061.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2058.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2060.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2059.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/heart/IMG_2062.PNG',
        sad_phrase: 'That broke me.',
        happy_phrase: 'Follow me next time.',
    },
    {
        name: 'rock',
        neutral: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1985.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1984.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1980.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1981.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/rock/IMG_1982.PNG',
        sad_phrase: 'First paper, now this.',
        happy_phrase: 'Rock beats you too!',
    },
    {
        name: 'horse',
        neutral: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1952.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1950.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1951.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1949.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/horse/IMG_1946.PNG',
        sad_phrase: 'I was just horsing around.',
        happy_phrase: 'Why the long face?',
    },
    {
        name: 'icecream',
        neutral: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1896.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1898.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1897.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1895.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/icecream/IMG_1893.PNG',
        sad_phrase: 'Now that was cold.',
        happy_phrase: 'Chill.',
    },
    {
        name: 'leaf',
        neutral: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1878.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1879.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1881.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1882.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/leaf/IMG_1880.PNG',
        sad_phrase: 'You blew me away.',
        happy_phrase: 'Leaf it to me.',
    },
    {
        name: 'orange',
        neutral: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1918.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1920.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1919.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1921.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/orange/IMG_1922.PNG',
        sad_phrase: 'That was less than a-peeling.',
        happy_phrase: 'Orange you glad I came?',
    },
    {
        name: 'cat',
        neutral: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1929.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1930.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1928.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1928.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/cat/IMG_1928.PNG',
        sad_phrase: 'Feline that one...',
        happy_phrase: 'How do you like meow?',
    },
    {
        name: 'pineapple',
        neutral: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1907.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1906.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1908.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1908.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/pineapple/IMG_1909.PNG',
        sad_phrase: 'Now I feel like a whine-apple.',
        happy_phrase: 'They call me the fine-apple.',
    },
    {
        name: 'pirate',
        neutral: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2091.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2092.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2091.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2093.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/pirate/IMG_2095.PNG',
        sad_phrase: 'You kicked my booty.',
        happy_phrase: 'Yo ho!',
    },
    {
        name: 'poop',
        neutral: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1974.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1969.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1973.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1972.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/poop/IMG_1971.PNG',
        sad_phrase: 'Poop!',
        happy_phrase: 'I can do this crap all day!',
    },
    {
        name: 'astronaut',
        neutral: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2152.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2149.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2152.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2152.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/astronaut/IMG_2151.PNG',
        sad_phrase: 'Houston, we have a problem.',
        happy_phrase: 'One small point for me.',
    },
    {
        name: 'raccoon',
        neutral: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1941.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1940.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1939.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_2064.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/raccoon/IMG_1962.PNG',
        sad_phrase: 'This is garbage.',
        happy_phrase: 'I made out like a bandit.',
    },
    {
        name: 'Whale',
        neutral: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_1935.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_1935.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_1937.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_1936.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/whale/IMG_1938.PNG',
        sad_phrase: 'Oh whale.',
        happy_phrase: '',
    },
    {
        name: 'rain',
        neutral: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2022.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2024.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2023.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2026.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/rain/IMG_2025.PNG',
        sad_phrase: 'Tut tut sounds like pain.',
        happy_phrase: 'Rain dropped the mic.',
    },
    {
        name: 'starfish',
        neutral: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2157.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2156.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2154.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2155.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/starfish/IMG_2153.PNG',
        sad_phrase: 'Something smells star-fishy',
        happy_phrase: `I'll make you sea stars!`,
    },
    {
        name: 'alien',
        neutral: process.env.PUBLIC_URL + '/data//avatars/alien/IMG_2107.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2159.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2108.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2109.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/alien/IMG_2158.PNG',
        sad_phrase: 'I spaced out...',
        happy_phrase: 'Outta this world!',
    },
    {
        name: 'sun-glasses',
        neutral: process.env.PUBLIC_URL + '/data/avatars/sun-glasses/IMG_2079.PNG',
        happy: process.env.PUBLIC_URL + '/data/avatars/sun-glasses/IMG_2082.PNG',
        suspicious: process.env.PUBLIC_URL + '/data/avatars/sun-glasses/IMG_2078.PNG',
        nervous: process.env.PUBLIC_URL + '/data/avatars/sun-glasses/IMG_2080.PNG',
        sad: process.env.PUBLIC_URL + '/data/avatars/sun-glasses/IMG_2081.PNG',
        sad_phrase: `I'm gonna need some aloe with that burn.`,
        happy_phrase: `Take that sun!`,
    },
]